# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 19:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('private_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
